// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/course/chapter/:chapterSession/lesson/:lessonSlug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/course/chapter/[chapterSession]/lesson/[lessonSlug].get').default>>>>
    }
    '/api/course/chapter/:chapterSession/lesson/:lessonSlug/progress': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/course/chapter/[chapterSession]/lesson/[lessonSlug]/progress').default>>>>
    }
    '/api/course/meta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/course/meta.get').default>>>>
    }
    '/api/midtrans/paymentIntent': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midtrans/paymentIntent').default>>>>
    }
    '/api/midtrans/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midtrans/webhook.post').default>>>>
    }
    '/api/user/hasAccess': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/hasAccess').default>>>>
    }
    '/api/user/linkWithPurchase/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/linkWithPurchase/[id]').default>>>>
    }
    '/api/user/progress': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/progress.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}